# Generated by Django 3.2.9 on 2021-11-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=64)),
                ('trade_name', models.CharField(max_length=64)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('address', models.CharField(max_length=255)),
                ('employees', models.ManyToManyField(to='employees.Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
