# Generated by Django 3.2.9 on 2021-11-21 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='trade_name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
